/* Tests the Cloudflare Worker gateway offline with a mocked upstream fetch. Run: node tests/worker.test.mjs */
import worker from "../worker/gateway.js";
import assert from "node:assert";
const seen = [];
globalThis.fetch = async (u, o = {}) => { seen.push({u: String(u), o});
  if (String(u).includes("anthropic")) return new Response("event: message_stop\ndata: {}\n\n", {status: 200, headers: {"content-type": "text/event-stream"}});
  if (String(u).includes("k.htm")) return new Response("<html><body><h2>Item 1A. Risk Factors</h2><p>Risk &amp; more.</p><script>x()</script></body></html>", {status: 200, headers: {"content-type": "text/html"}});
  if (String(u).includes("access_token")) return new Response(JSON.stringify({access_token: "rt", expires_in: 3600}), {status: 200});
  if (String(u).includes("oauth.reddit.com")) return new Response(JSON.stringify({data: {children: [{data: {id: "a1", title: "WTTR DD", selftext: "long", subreddit: "stocks", author: "u", score: 12, num_comments: 4, created_utc: 1790000000, permalink: "/r/stocks/comments/a1/"}}]}}), {status: 200});
  if (String(u).includes("googleapis.com/youtube")) return new Response(JSON.stringify({items: [{id: {videoId: "v1"}, snippet: {title: "WTTR review", description: "d", channelTitle: "c", publishedAt: "2026-09-30T00:00:00Z"}}]}), {status: 200});
  return new Response(JSON.stringify({ok: 1}), {status: 200, headers: {"content-type": "application/json"}}); };
const env = {ACCESS_TOKEN: "tok", SEC_USER_AGENT: "Test t@example.com", ANTHROPIC_API_KEY: "sk-x"}, ctx = {waitUntil() {}};
const call = (path, init = {}) => worker.fetch(new Request("https://gw.example" + path, init), env, ctx);
let r = await call("/"); assert.equal(r.status, 200); console.log("  ✓ health", await r.text());
r = await call("/fetch?url=" + encodeURIComponent("https://data.sec.gov/x.json")); assert.equal(r.status, 401); console.log("  ✓ token required");
r = await call("/fetch?url=" + encodeURIComponent("https://evil.com/x"), {headers: {"x-aic-token": "tok"}}); assert.equal(r.status, 403); console.log("  ✓ host allow-list");
r = await call("/fetch?url=" + encodeURIComponent("https://data.sec.gov/x.json"), {headers: {"x-aic-token": "tok"}}); assert.equal(r.status, 200); assert.equal(r.headers.get("access-control-allow-origin"), "*");
assert.equal(seen.at(-1).o.headers["User-Agent"], "Test t@example.com"); console.log("  ✓ SEC fetch with User-Agent + CORS");
r = await call("/fetch?text=1&url=" + encodeURIComponent("https://www.sec.gov/Archives/k.htm"), {headers: {"x-aic-token": "tok"}}); const t = await r.text(); assert.ok(t.includes("Risk & more") && !t.includes("<p>") && !t.includes("x()")); console.log("  ✓ HTML stripped:", JSON.stringify(t));
r = await call("/anthropic/v1/messages", {method: "POST", headers: {"x-aic-token": "tok", "content-type": "application/json"}, body: "{}"}); assert.equal(r.status, 200); assert.equal(seen.at(-1).o.headers["x-api-key"], "sk-x"); console.log("  ✓ Anthropic proxy adds the key");
const env2 = {ACCESS_TOKEN: "tok"};
r = await worker.fetch(new Request("https://gw.example/anthropic/v1/messages/batches/msgbatch_1", {headers: {"x-aic-token": "tok", "x-api-key": "sk-user"}}), env2, ctx);
assert.equal(r.status, 200); assert.equal(seen.at(-1).o.headers["x-api-key"], "sk-user"); assert.equal(seen.at(-1).o.method, "GET"); console.log("  ✓ Batch status GET forwarded with the app's key");
r = await call("/fetch?url=" + encodeURIComponent("https://api.stocktwits.com/api/2/streams/symbol/WTTR.json"), {headers: {"x-aic-token": "tok"}}); assert.equal(r.status, 200); console.log("  ✓ StockTwits host allowed");
r = await call("/reddit?q=WTTR", {headers: {"x-aic-token": "tok"}}); assert.equal(r.status, 501); console.log("  ✓ Reddit not set up → 501");
const env3 = {ACCESS_TOKEN: "tok", REDDIT_CLIENT_ID: "id", REDDIT_CLIENT_SECRET: "sec", YOUTUBE_API_KEY: "yk"};
r = await worker.fetch(new Request("https://gw.example/reddit?q=WTTR&t=week", {headers: {"x-aic-token": "tok"}}), env3, ctx); let j = await r.json();
assert.equal(j.posts[0].url, "https://www.reddit.com/r/stocks/comments/a1/"); assert.equal(seen.at(-1).o.headers.authorization, "Bearer rt"); console.log("  ✓ Reddit search with app-only login");
r = await worker.fetch(new Request("https://gw.example/youtube?q=WTTR", {headers: {"x-aic-token": "tok"}}), env3, ctx); j = await r.json();
assert.equal(j.videos[0].url, "https://www.youtube.com/watch?v=v1"); assert(!JSON.stringify(j).includes("yk")); console.log("  ✓ YouTube search (key stays on the gateway)");
r = await worker.fetch(new Request("https://gw.example/"), env3, ctx); j = await r.json(); assert(j.reddit && j.youtube); console.log("  ✓ health reports reddit/youtube");
r = await call("/fetch", {method: "OPTIONS"}); assert.equal(r.status, 204); console.log("  ✓ CORS preflight");
console.log("All worker tests passed.");
